
   interface Article {
  id: number;
  image: string;
  date: string;
  title: string;
  contentshort: string;
  btn1 ?:string;
  btn2 ?:string;
  btn3 ?:string;

};
export interface Allinfo {
    id : number;
    part1 : string;
    defind : string;
    defind2 : string;
    defind3 : string;
    defind4 : string;
    defind5 : string;
    defind6 : string;
    part2 : string;
    part3 : string;
    part4 : string;
    part5 : string;
    part6 : string;
    part7 : string;
    part8 : string;
    part9 : string;
    part10 : string;
    part11 : string;
    part12 : string;
    part13 : string;
    part14 : string;
    part15 : string;
    part16 : string;
    part17 : string;
    part18 : string;
    part19 : string;
    part20 : string;
    part21 : string;
    part22 : string;
    part23 : string;
    part24 : string;
   ex1:string;
   ex2:string;
   ex3:string;
   ex4:string;
   image1 : string;
   image2 : string;
   image3 : string;
   image4 : string;
   image5 : string;
   image6 : string;
   image7 : string;
   image8 : string;
   image9 : string;

}
 export type ArticleState = {
  articles: Article[];
  currentPage: number;
  pageSize: number;
  mainArticle : any;
  twoArticle : any;
  fourArticle : any;
  nineitem : any;
  threeitem : any;
  Allinfo: Allinfo []
};
const initialState : ArticleState= {
  articles: [
    { id: 1,
    image: "/TaskAdv6/assets/image/home/Image (2).png",
    date:"Olivia Rhye • 1 Jan 2023",
    title: "UX review presentations", 
    contentshort: "How do you create compelling presentations that wow your colleagues and impress your managers?",
    btn1:"Design" ,
    btn2: "Research" ,
    btn3 : "Presentation"
     },
    { id: 2,
    image: "/TaskAdv6/assets/image/home/Image (3).png",
    date:"Phoenix Baker • 1 Jan 2023",
    title: "Migrating to Linear 101", 
    contentshort: "Linear helps streamline software projects, sprints, tasks, and bug tracking. Here’s how to get...",
    btn1:"Design" ,
    btn2: "Research" ,
     },
    { id: 3,
    image: "/TaskAdv6/assets/image/home/Image (4).png",
    date:"Lana Steiner • 1 Jan 2023",
    title: "Building your API Stack", 
    contentshort: "The rise of RESTful APIs has been met by a rise in tools for creating, testing, and manag...",
    btn1:"Design" ,
    btn2: "Research" ,
     },
    { id: 4,
        image: "/TaskAdv6/assets/image/home/Image (5).png",
    date:"Olivia Rhye • 1 Jan 2023",
    title: "Grid system for better Design User Interface", 
    contentshort: "A grid system is a design tool used to arrange content on a webpage. It is a series of vertical and horizontal lines that create a matrix of intersecting points, which can be used to align and organize page elements. Grid systems are used to create a consistent look and feel across a website, and can help to make the layout more visually appealing and easier to navigate.",
    btn1:"Design" ,
    btn2: "Interface" ,
     },
    { id: 5,
    image: "/TaskAdv6/assets/image/home/Image (6).png",
    date:"Alec Whitten • 1 Jan 2023",
    title: "Bill Walsh leadership lessons", 
    contentshort: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    btn1:"Leadership" ,
    btn2: "Management" ,
    
     },
    { id: 6,
        image: "/TaskAdv6/assets/image/home/Image (7).png",
    date:"Demi WIlkinson • 1 Jan 2023",
    title: "PM mental models", 
    contentshort: "Mental models are simple expressions of complex processes or relationships.",
    btn1:"Product" ,
    btn2: "Research" ,
    btn3 : "Frameworks"
     
     },
    { id: 7,
        image: "/TaskAdv6/assets/image/home/Image (8).png",
    date:"Candice Wu • 1 Jan 2023",
    title: "What is Wireframing?", 
    contentshort: "Introduction to Wireframing and its Principles. Learn from the best in the industry.",
    btn1:"Product" ,
    btn2: "Research" ,
    
     },
    { id: 8,
        image: "/TaskAdv6/assets/image/home/Image (9).png",
    date:"Natali Craig • 1 Jan 2023",
    title: "How collaboration makes us better designers", 
    contentshort: "Collaboration can make our teams stronger, and our individual designs better.",
    btn1: "Design",
    btn2: "Research"
     },
    { id: 9,
        image: "/TaskAdv6/assets/image/home/Image (10).png",
    date:"Drew Cano • 1 Jan 2023",
    title: "Our top 10 Javascript frameworks to use", 
    contentshort: "JavaScript frameworks make development easy with extensive features and functionalities.",
       btn1: "Software Development",
    btn2: "Tools",
    btn3: "SaaS"
     },
  
    { id: 10,
    image: "/TaskAdv6/assets/image/home/Image (11).png",
    date:"Orlando Diggs • 1 Jan 2023",
    title: "Podcast: Creating a better CX Community", 
    contentshort: "Starting a community doesn’t need to be complicated, but how do you get started?",
    btn1: "Podcasts",
    btn2 :"Customer Success"

     },
  
    { id: 11,
        image: "/TaskAdv6/assets/image/home/Image (3).png",
    date: "Riley Nguyen • 1 Jan 2023",
    title: "Design systems: How to scale consistency",
    contentshort: "Design systems help large teams create cohesive, consistent UI while moving fast."
    },
    { id: 12,
        image: "/TaskAdv6/assets/image/home/Image (4).png",
    date: "Morgan Fisher • 1 Jan 2023",
    title: "Introduction to Scrum methodology",
    contentshort: "Scrum is a framework that helps teams work together—learn how it supports agile project management."
    },
    { id: 13,
        image: "/TaskAdv6/assets/image/home/Image (5).png",
    date: "Jamie Lane • 1 Jan 2023",
    title: "Accessibility in UI design",
    contentshort: "Designing for everyone means embracing"},
    { id: 14,
        image: "/TaskAdv6/assets/image/home/Image (6).png",
    date: "Casey Tran • 1 Jan 2023",
    title: "Microinteractions in product design",
    contentshort: "These small animations can delight users and provide helpful feedback along the way."
    },
    { id: 15,
        image: "/TaskAdv6/assets/image/home/Image (7).png",
    date: "Jordan Lee • 1 Jan 2023",
    title: "Lean UX: Speed without sacrifice",
    contentshort: "Lean UX encourages rapid experimentation and iteration without compromising usability."
    },
    { id: 16,
        image: "/TaskAdv6/assets/image/home/Image (8).png",
    date: "Taylor Evans • 1 Jan 2023",
    title: "Principles of effective onboarding",
    contentshort: "A smooth onboarding experience can reduce churn and set users up for long-term success."
    },
    { id: 17,
        image: "/TaskAdv6/assets/image/home/Image (9).png",
    date: "Skylar Brooks • 1 Jan 2023",
    title: "Figma tips for faster workflows",
    contentshort: "Power users swear by these hidden gems and time-saving tricks inside Figma."
    },
    { id: 18,
        image: "/TaskAdv6/assets/image/home/Image (10).png",
    date: "Remy Park • 1 Jan 2023",
    title: "Dark mode design best practices",
    contentshort: "Dark mode isn't just trendy—it improves accessibility and reduces eye strain when used right."
    },
    { id: 19,
        image: "/TaskAdv6/assets/image/home/Image (11).png",
    date: "Dakota Shaw • 1 Jan 2023",
    title: "Design handoff: Bridging the gap",
    contentshort: "A seamless transition from design to development minimizes rework and boosts efficiency."
    },
    { id: 20,
        image: "/TaskAdv6/assets/image/home/Image (2).png",
    date: "Kendall Morris • 1 Jan 2023",
    title: "Creating inclusive forms",
    contentshort: "Forms that consider diverse user needs contribute to a more inclusive user experience."
    }

  ],
    currentPage: 1,
    pageSize: 6,
    mainArticle :null,
    twoArticle :null,
    fourArticle : null,
    nineitem : null,
    threeitem : null , 
  Allinfo:[
    {
        id:1,
        part1: "A grid system is a design tool used to arrange content on a webpage. It is a series of vertical and horizontal lines that create a matrix of intersecting points, which can be used to align and organize page elements. Grid systems are used to create a consistent look and feel across a website, and can help to make the layout more visually appealing and easier to navigate.If you’ve been to New York City and have walked the streets, it is easy to figure out how to get from one place to another because of the grid system that the city is built on. Just as the predictability of a city grid helps locals and tourists get around easily, so do webpage grids provide a structure that guides users and designers alike. Because of their consistent reference point, grids improve page readability and scannability and allow people to quickly get where they need to go.",
        defind: "Definition: A grid is made up of columns, gutters, and margins that provide a structure for the layout of elements on a page.",
        defind2:"Definition: A grid is made up of columns, gutters, and margins that provide a structure for the layout of elements on a page.",
        part2: "There are three common grid types used in websites and interfaces: column grid, modular grid, and hierarchical grid.Column grid involves dividing a page into vertical columns. UI elements and content are then aligned to these columns.Modular grid extends the column grid further by adding rows to it. This intersection of columns and rows make up modules to which elements and content are aligned. Modular grids are great for ecommerce and listing pages, as rows are repeatable to accommodate browsing.Hierarchical grid: Content is organized by importance using columns, rows, and modules. The most important elements and pieces of content take up the biggest pieces of the grid.",
        defind3:"Breaking Down the Grid",
        part3: "Regardless of the type of grid you are using, the grid is made up of three elements: columns, gutters, and margins.",
        part4:"Columns take up most of the real estate in a grid. Elements and content are placed in columns. To adapt to any screen size, column widths are generally defined with percentages rather than fixed values and the number of columns will vary. For example, a grid on a mobile device might have 4 columns and a grid on a desktop might have 12 columns.",
        part5:"The gutter is the space between columns that separates elements and content from different columns. Gutter widths are fixed values but can change based on different breakpoints. For example, wider gutters are appropriate for larger screens, whereas smaller gutters are appropriate for smaller screens like mobile.",
        ex1:"Examples of Grids in Use Example 1: Hierarchical Grid",
        part6:"Our first example is from The New York Times. This screen utilizes a hierarchical grid to create a newspaper-like reading experience. At desktop screen size, two main columns make up the hierarchical grid. The most important news story takes up the most space in the grid, the left column, followed by secondary and tertiary stories, which take up the smaller column and modules on the right.",
        part7:"The New York Times uses a hierarchical grid to achieve its newspaper-like reading experience. (We highlighted the columns in yellow, the gutters in blue, and the margins in purple.)",
        ex2:"Example 2: Column Grid",
        part8:"Our second example is from Ritual.com, a vitamin company. This design uses a column grid to create an attractive visual experience. At this screen size, four consistently sized columns make up the grid structure and elements are aligned to and within these columns. The gutters, the spaces in between the columns, are also consistently sized and help the user visually separate the different products. The margins are independently sized and are the same between the left and right sides.",
        part9:"Ritual’s four-column grid makes scanning products easy. (We highlighted the columns in yellow, the gutters in blue, and the margins in purple.)",
        ex3:"Example 3: Modular Grid",
        part10:"Our third example is from Behance, a design library. The site’s design uses a modular grid to create a pleasant browsing experience. At desktop size, rows are made up of 4 consistently sized modules. Horizontal gutters are slightly thicker than vertical gutters and the margins are consistently sized on the left and right of the design. Like in previous example, the gutters visually separate each element.",
        part11:"Behance’s design uses a modular grid, which allows users to easily browse. (We highlighted the columns in yellow, the gutters in blue, and the margins in purple.)",
        ex4:"Example 4: Breaking the Grid",
        part12:"Our last example is Shrine from Google’s Material Studies. This design uses a column grid, as we can see based on the left navigation, which is 2 columns wide. Look closely and you will see that some product images settle to the margins, while others do not. Breaking the grid like this makes it challenging to focus or quickly scan product images and calls more attention to some products over others. It is okay to break the grid every so often, as long as you have a valid reason for it.",
        part13:"Breaking the grid produces a chaotic browsing experience for users. (We highlighted the columns in yellow, the gutters in blue, and the margins in purple.)",
        defind4:"Benefits of the Grid",
        part14:"Using a grid benefits both end users and the designers alike:Designers can quickly put together well-aligned interfaces.Users can easily scan predictable grid-based interfaces.A good grid is easy to adapt to various screen sizes and orientations. In fact, grid layouts are an essential component of responsive web design. Responsive design uses breakpoints to determine the screen size threshold at which the layout should change. For example, a desktop screen may have 12 grid columns, which may be stacked on mobile so that the resulting layout has only 4 columns.",
        part15:"At the mobile size, Behance’s one-column grid (left) was reflowed into a four-column grid structure (right).",
        part16:"Even more importantly, the grid is not a throw-away concept. It is used by both designers and developers alike. Be sure to communicate with your developers the grid structure used when creating the design, so they can implement it accordingly.",
        defind5:"Choosing and Setting Up Your Grid",
        part17:"How you use and set up a grid is fundamental to creating well thought out layouts and experiences for your user.",
        part18:"Choose the right grid for your needs. Take time to think through what type of grid ­— column, modular, or hierarchical — best suits your needs. A hierarchical grid may be the best fit if one item on your page will always be more important than the surrounding elements. For example, hierarchical grids are great for online news platforms. If the content you need to display is highly variable, consider using a basic column or modular grid, as these provide lots of flexibility when designing. For example, elements and content can span across multiple columns or modules or just one to fit design needs.",
        part19:"Spend time setting up your grid. Once you have figured out what type of grid will work well for your needs, start setting it up. Determine the number of columns and the margin and gutter sizes relative to your screen sizes. You will most likely want to prepare for mobile, tablet, and desktop screens. A 12-column grid at laptop or desktop size is generally flexible enough for most design needs. The number of columns will decrease as your device size decreases. Wireframing tools like Sketch and Figma have quick and easy ways to set up and edit your grid, even after you have started designing.",
        part20:"Easily set the number of columns, the gutter size, and margin size in Figma.",
        part21:"Always place content within columns, not gutters. The gutters should remain empty as you place elements on the grid in order to clearly separate and align content and elements.",
        part22:"Content or elements should be placed within and across columns, not gutters.",
        part23:"Consider using an 8px grid system. For most common devices, the screen size in pixels is a multiple of 8. Keeping grid-component values at a multiple of 8 will generally make it easier to scale and implement a grid.",
        defind6:"Conclusion",
        part24:"Grids not only provide designers a structure on which to base layouts, but they also improve readability and scannability for end users. Use a good grid system that easily adapts to various screen sizes.",
        image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",
    },
      {
    id: 2,
    part1: "Color theory in design helps us choose harmonious color combinations that support a product's message and emotional tone. Using colors intentionally can guide user attention and convey personality.",
    defind: "Definition: Color theory is the science and art of using color to evoke specific emotions and create visual consistency.",
    defind2: "Definition: Color harmonies are specific combinations of colors that appear pleasing together.",
    part2: "Designers often rely on three main color systems: monochromatic, complementary, and analogous. Monochromatic schemes use shades of a single color. Complementary colors sit opposite on the color wheel, and analogous colors sit side-by-side.",
    defind3: "Color Structures and Meaning",
    part3: "Each color carries associations—blue conveys trust, red expresses urgency, and green evokes nature. These meanings vary slightly across cultures but are foundational in digital design.",
    part4:"Choosing the right primary and secondary palette ensures visual clarity and identity alignment across a product.",
    part5: "Contrast is critical for accessibility. High-contrast text on backgrounds improves readability and ensures compliance with accessibility standards.",
    ex1: "Example 1: Monochromatic Design",
    part6: "Dropbox uses shades of blue across UI components to convey trust and keep its experience cohesive.",
    part7: "Consistent use of one hue allows for a calm, focused user experience.",
    ex2: "Example 2: Complementary Colors",
    part8: "Slack’s branding combines purples with greens for balance and vibrant contrast.",
    part9: "This approach grabs attention while maintaining visual stability.",
    ex3: "Example 3: Analogous Palette",
    part10: "Spotify uses green with nearby yellows and blues for a smooth, modern vibe.",
    part11: "Analogous color schemes support natural transitions in background and elements.",
    ex4: "Example 4: Color Contrast",
    part12: "Apple’s marketing pages often pair stark black text with white backgrounds for maximum readability.",
    part13: "Strong contrast ensures that content stands out even with minimal design.",
    defind4: "Benefits of Color Theory",
    part14: "Colors not only enhance branding but also improve usability, guide user flow, and increase engagement. Good color choices highlight key elements without overwhelming the layout.",
    part15: "Using consistent palette values across UI states—hover, active, disabled—builds trust and predictability.",
    part16: "Accessibility tools like contrast checkers and WCAG guidelines assist in making inclusive choices.",
    defind5: "Building a Color System",
    part17: "Start by selecting a primary color that aligns with your brand’s emotion. Then, build out supporting tones for various components like backgrounds, alerts, and buttons.",
    part18: "Tools like Adobe Color and Coolors can help you generate palettes and test combinations instantly.",
    part19: "Always preview your design in light and dark mode to ensure your palette works across themes.",
    part20: "Document color tokens (e.g., `primary-100`, `primary-800`) and share them with the dev team for implementation.",
    part21: "Never rely solely on color to convey meaning—use icons or text as backup indicators.",
    part22: "Accessibility-first design treats color as one layer of communication, not the only one.",
    part23: "Neutral tones (grays, beiges) are ideal for text and background balance.",
    defind6: "Conclusion",
    part24: "Color, when used wisely, can elevate design from average to exceptional. Understanding theory helps you make bold, effective visual decisions.",
        image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",
  },
    {
    id: 3,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
        image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",  
},
    {
    id: 4,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
       image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",   
},
    {
    id: 5,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
  image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",  
},
    {
    id: 6,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
     image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",
},
    {
    id: 7,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
     image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",   
},
    {
    id: 8,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
    image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",    
},
    {
    id: 9,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
     image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",   
},
    {
    id: 10,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
     image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",  
},
    {
    id: 11,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
        image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",  
},
    {
    id: 12,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
     image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png", 
},
    {
    id: 13,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
    image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",    
},
    {
    id: 14,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
    image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",    
},
    {
    id: 15,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",   
},
    {
    id: 16,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
   image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",   
},
    {
    id: 17,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
    image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",   
},
    {
    id: 18,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
   image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",    
},
    {
    id: 19,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
 image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",   
},
    {
    id: 20,
    part1: "Typography isn’t just about choosing a pretty font—it’s about establishing clear hierarchy, improving readability, and expressing brand voice through textual elements.",
    defind: "Definition: Typography is the art and technique of arranging type to make written language legible, readable, and visually engaging.",
    defind2: "Definition: Hierarchy in typography organizes content by order of importance using font size, weight, and spacing.",
    part2: "There are generally three type categories: serif, sans-serif, and display. Serif fonts convey tradition and formality, sans-serifs suggest modernity and clarity, while display fonts serve decorative purposes.",
    defind3: "Typography System",
    part3: "A well-structured system includes multiple font sizes, weights, and line heights for headers, body, and captions. Consistency across these elements builds trust and professionalism.",
    part4: "Body text should typically use 16px as a base size with 1.5 line spacing for optimal reading comfort on web.",
    part5: "Letter spacing (tracking) and line height must be tested across multiple screen widths to maintain legibility.",
    ex1: "Example 1: Clear Heading Hierarchy",
    part6: "Medium uses H1, H2, and body styles predictably, drawing attention to headlines while making articles easy to read.",
    part7: "The consistent use of spacing and font weight helps guide the eye naturally.",
    ex2: "Example 2: Brand Typography",
    part8: "Google uses Product Sans for its branding—custom, geometric, and minimal, reflecting their clean and modern design approach.",
    part9: "Typography becomes a brand signature that users instantly recognize.",
    ex3: "Example 3: Multi-language Fonts",
    part10: "Airbnb supports global users with font stacks that include Latin, Cyrillic, Arabic, and Chinese characters.",
    part11: "Ensuring character compatibility is crucial for consistent experience.",
    ex4: "Example 4: Responsive Text",
    part12: "Dropbox scales headings and adjusts line height dynamically based on viewport width.",
    part13: "This responsive approach ensures clarity across devices.",
    defind4: "Benefits of Strong Typography",
    part14: "Proper typography builds credibility, helps users scan faster, and makes interfaces more pleasant to interact with.",
    part15: "Emphasizing contrast between title and body prevents content fatigue.",
    part16: "Readable fonts reduce cognitive load and boost overall engagement.",
    defind5: "Designing with Type",
    part17: "Start with a base type scale—select one font for headings and one for body. Avoid using too many fonts.",
    part18: "Use modular scale ratios like 1.25x or 1.333x to size headings proportionally.",
    part19: "Pair fonts that have contrast in weight but harmony in character width.",
    part20: "Test your font system on real content, not placeholders.",
    part21: "Avoid all-uppercase text for paragraphs—it reduces legibility.",
    part22: "Use bold or color to highlight, but keep things subtle.",
    part23: "Limit font weights to 400, 500, and 700 to simplify design implementation.",
    defind6: "Conclusion",
    part24: "Strong typography is the backbone of digital communication. It unites clarity with aesthetics, giving life to content.",
    image1: "/TaskAdv6/assets/image/blog/Image.png",
        image2: "/TaskAdv6/assets/image/blog/Image (1).png",
        image3: "/TaskAdv6/assets/image/blog/Image (2).png",
        image4: "/TaskAdv6/assets/image/blog/Image (3).png",
        image5: "/TaskAdv6/assets/image/blog/Image (4).png",
        image6: "/TaskAdv6/assets/image/blog/Image (5).png",
        image7: "/TaskAdv6/assets/image/blog/Image (6).png",
        image8: "/TaskAdv6/assets/image/blog/Image (7).png",
        image9: "/TaskAdv6/assets/image/blog/Image (11).png",    
},
  ]

};



export default initialState;